baseURL = 'https://stetsed.xyz'
languageCode = 'en-us'
title = "Stetsed's Guides"
theme = 'PaperMod'

buildDrafts = false
buildFuture = false
buildExpired = false

[minify]
  disableXML = true
  minifyOutput = true

[params]
env = "production"
title = "Stetsed's Guides"
description = "Welcome to my blog, with my guides for stuff I need to remember!"
keywords = [ "Blog", "Hugo", "PaperMod", "Stetsed", "VFIO", "Framework", "Framework13", "Framework Laptop", "Arch Linux", "Linux"]
author = "Stetsed"
DateFormat = "January 2, 2006"
defaultTheme = "dark"
disableThemeToggle = false
ShowReadingTime = true
ShowShareButtons = false
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = true
ShowWordCount = true
ShowRssButtonInSectionTermList = true
UseHugoToc = false
disableSpecial1stPost = false
disableScrollToTop = false
comments = false
hidemeta = false
hideSummary = false
showtoc = true
tocopen = false
mainSections = ["posts"]

  [params.label]
  text = "Home"
  icon = "/apple-touch-icon.png"
  iconHeight = 35

  [params.profileMode]
  enabled = false
  title = "Stetsed's Guides"
  subtitle = "Welcome to my blog, with my guides for stuff I need to remember!"

    [[params.profileMode.buttons]]
    name = "Posts"
    url = "posts"

    [[params.profileMode.buttons]]
    name = "Tags"
    url = "tags"

  [params.homeInfoParams]
  Title = "Hi there, Welcome to Stetsed's Guides 👋"
  Content = "Welcome to my blog, with my guides for stuff I need to remember!"

  [[params.socialIcons]]
  name = "github"
  url = "https://github.com/Stetsed"

  [[params.socialIcons]]
  name = "email"
  url = "mailto:stetsed@protonmail.com"

  [params.cover]
  hidden = true
  hiddenInList = true
  hiddenInSingle = true

  [params.editPost]
  URL = "https://github.com/stetsed/stetsed-guides/blob/main/content"
  Text = "Suggest Changes"
  appendFilePath = true

  [params.fuseOpts]
  isCaseSensitive = false
  shouldSort = true
  location = 0
  distance = 1_000
  threshold = 0.4
  minMatchCharLength = 0
  keys = [ "title", "permalink", "summary", "content" ]

[[menu.main]]
identifier = "Tags"
name = "Tags"
url = "/tags/"
weight = 30

[[menu.main]]
identifier = "Info"
name = "Info"
url = "/info/"
weight = 20

[markup.highlight]
noClasses = false
guessSyntax = true
codefences = true
lineNos = true

[Params.umami]
  enabled = true
  websiteId = "93131be9-87e5-4164-9cf0-1394c09ab0d6"
  jsLocation = "https://analytics.stetsed.xyz/script.js"

